### ISSUE TITLE
GitHub Actions: Continuous Integration の Step 11 の commit suggestion の行がずれている

### ISSUE THREAD

**Issue by dzeyelid** [zengeeks/devops-workshop-basic#4]
### 現象

[GitHub Actions: Continuous Integration](https://lab.github.com/githubtraining/github-actions:-continuous-integration) のコンテンツの Step 11 で、`build` job に `actions/upload-artifact` を追加する commit suggestion の行がずれている。

![image](https://user-images.githubusercontent.com/977117/122206127-fcd66200-cedb-11eb-8fef-efcfec09cdfa.png)

This issue is raised as githubtraining/using-github-actions-for-ci#56 already.

### 対処（一時的）

Commit suggestion は利用せず、コードを直接編集し、 `build` job の最後のステップに、下記を追加する。（インデントに気を付けて）

```
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/
```
